/**:
  smartec_motor_driver:
    ros__parameters:
      interface: "socketcan"
      channel: "can32"
      bitrate: 500000
      command_rate: 50
      status_rate: 20
      odom_rate: 50 
      base_width: 0.82
      wheel_radius: 0.1825
      gear_ratio: 10.85625
      idle_timeout: 0.25
      debug: false
      rpm_control_mode: 2
      hard_stop_mode: 1